---
version: "2"
services:
  motioneye:
    image: ccrisan/motioneye:master-armhf  # Change to ccrisan/motioneye:master-armhf for ARM chips (Pi etc.)
    ports:
      - "80:8765"
    volumes:
      - /home/pi/motioneye/etc:/etc/motioneye
      - /home/pi/motioneye/media:/var/lib/motioneye
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

